
[auth]
cookie_name = "ai_quiz_auth"
cookie_key = "a-long-random-secret"
expiry_days = 7

# Example users
usernames = ["alice", "bob"]
names = ["Alice", "Bob"]
# Paste the list of hashed passwords from the script above:
hashed_passwords = ["$2b$12$...","$2b$12$..."]